package com.gympal.admin;

public enum GymFeatureKey {
    MEMBER_MANAGEMENT,
    ATTENDANCE_CHECKIN,
    DIET_WORKOUT_PLANS,
    ONLINE_PAYMENTS,
    SMS_WHATSAPP_NOTIFICATIONS,
    CUSTOM_BRANDING,
    ANALYTICS_REPORTS,
    STAFF_MANAGEMENT,
    MULTI_BRANCH_SUPPORT
}
